PROJECT=jdksavdecc-c
PROJECT_NAME=jdksavdecc-c
PROJECT_VERSION?=20130629
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=BSD
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2013
PROJECT_DESCRIPTION=
PROJECT_WEBSITE=https://jdksavdecc-c.statusbar.com/
PROJECT_IDENTIFIER=org.statusbar.jdksavdecc-c
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
TEST_OUT_SUFFIX=txt

CONFIG_TOOLS=

COMPILE_FLAGS+=-Wall -Werror -W

