#pragma once
#ifndef JDKSAVDECC_AEM_COMMAND_H
#define JDKSAVDECC_AEM_COMMAND_H

/*
  Copyright (c) 2013, J.D. Koftinoff Software, Ltd.
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.

   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

   3. Neither the name of J.D. Koftinoff Software, Ltd. nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
*/

#include "jdksavdecc_world.h"
#include "jdksavdecc_aecp_aem.h"


/** \addtogroup command */
/*@{*/

#define JDKSAVDECC_AEM_COMMAND_SIZE (524) /// Clause 9.2.1.1.7

/*@}*/

/** \addtogroup command command : Command Codes - Clause 7.4  */
/*@{*/

#define JDKSAVDECC_AEM_COMMAND_ACQUIRE_ENTITY (0x0000)
#define JDKSAVDECC_AEM_COMMAND_LOCK_ENTITY (0x0001)
#define JDKSAVDECC_AEM_COMMAND_ENTITY_AVAILABLE (0x0002)
#define JDKSAVDECC_AEM_COMMAND_CONTROLLER_AVAILABLE (0x0003)
#define JDKSAVDECC_AEM_COMMAND_READ_DESCRIPTOR (0x0004)
#define JDKSAVDECC_AEM_COMMAND_WRITE_DESCRIPTOR (0x0005)
#define JDKSAVDECC_AEM_COMMAND_SET_CONFIGURATION (0x0006)
#define JDKSAVDECC_AEM_COMMAND_GET_CONFIGURATION (0x0007)
#define JDKSAVDECC_AEM_COMMAND_SET_STREAM_FORMAT (0x0008)
#define JDKSAVDECC_AEM_COMMAND_GET_STREAM_FORMAT (0x0009)
#define JDKSAVDECC_AEM_COMMAND_SET_VIDEO_FORMAT (0x000a)
#define JDKSAVDECC_AEM_COMMAND_GET_VIDEO_FORMAT (0x000b)
#define JDKSAVDECC_AEM_COMMAND_SET_SENSOR_FORMAT (0x000c)
#define JDKSAVDECC_AEM_COMMAND_GET_SENSOR_FORMAT (0x000e)
#define JDKSAVDECC_AEM_COMMAND_SET_STREAM_INFO (0x000d)
#define JDKSAVDECC_AEM_COMMAND_GET_STREAM_INFO (0x000f)
#define JDKSAVDECC_AEM_COMMAND_SET_NAME (0x0010)
#define JDKSAVDECC_AEM_COMMAND_GET_NAME (0x0011)
#define JDKSAVDECC_AEM_COMMAND_SET_ASSOCIATION_ID (0x0012)
#define JDKSAVDECC_AEM_COMMAND_GET_ASSOCIATION_ID (0x0013)
#define JDKSAVDECC_AEM_COMMAND_SET_SAMPLING_RATE (0x0014)
#define JDKSAVDECC_AEM_COMMAND_GET_SAMPLING_RATE (0x0015)
#define JDKSAVDECC_AEM_COMMAND_SET_CLOCK_SOURCE (0x0016)
#define JDKSAVDECC_AEM_COMMAND_GET_CLOCK_SOURCE (0x0017)
#define JDKSAVDECC_AEM_COMMAND_SET_CONTROL (0x0018)
#define JDKSAVDECC_AEM_COMMAND_GET_CONTROL (0x0019)
#define JDKSAVDECC_AEM_COMMAND_INCREMENT_CONTROL (0x001a)
#define JDKSAVDECC_AEM_COMMAND_DECREMENT_CONTROL (0x001b)
#define JDKSAVDECC_AEM_COMMAND_SET_SIGNAL_SELECTOR (0x001c)
#define JDKSAVDECC_AEM_COMMAND_GET_SIGNAL_SELECTOR (0x001d)
#define JDKSAVDECC_AEM_COMMAND_SET_MIXER (0x001e)
#define JDKSAVDECC_AEM_COMMAND_GET_MIXER (0x001f)
#define JDKSAVDECC_AEM_COMMAND_SET_MATRIX (0x0020)
#define JDKSAVDECC_AEM_COMMAND_GET_MATRIX (0x0021)
#define JDKSAVDECC_AEM_COMMAND_START_STREAMING (0x0022)
#define JDKSAVDECC_AEM_COMMAND_STOP_STREAMING (0x0023)
#define JDKSAVDECC_AEM_COMMAND_REGISTER_UNSOLICITED_NOTIFICATION (0x0024)
#define JDKSAVDECC_AEM_COMMAND_DEREGISTER_UNSOLICITED_NOTIFICATION (0x0025)
#define JDKSAVDECC_AEM_COMMAND_IDENTIFY_NOTIFICATION (0x0026)
#define JDKSAVDECC_AEM_COMMAND_GET_AVB_INFO (0x0027)
#define JDKSAVDECC_AEM_COMMAND_GET_AS_PATH (0x0028)
#define JDKSAVDECC_AEM_COMMAND_GET_COUNTERS (0x0029)
#define JDKSAVDECC_AEM_COMMAND_REBOOT (0x002a)
#define JDKSAVDECC_AEM_COMMAND_GET_AUDIO_MAP (0x002b)
#define JDKSAVDECC_AEM_COMMAND_ADD_AUDIO_MAPPINGS (0x002c)
#define JDKSAVDECC_AEM_COMMAND_REMOVE_AUDIO_MAPPINGS (0x002d)
#define JDKSAVDECC_AEM_COMMAND_GET_VIDEO_MAP (0x002e)
#define JDKSAVDECC_AEM_COMMAND_ADD_VIDEO_MAPPINGS (0x002f)
#define JDKSAVDECC_AEM_COMMAND_REMOVE_VIDEO_MAPPINGS (0x0030)
#define JDKSAVDECC_AEM_COMMAND_GET_SENSOR_MAP (0x0031)
#define JDKSAVDECC_AEM_COMMAND_ADD_SENSOR_MAPPINGS (0x0032)
#define JDKSAVDECC_AEM_COMMAND_REMOVE_SENSOR_MAPPINGS (0x0033)
#define JDKSAVDECC_AEM_COMMAND_START_OPERATION (0x0034)
#define JDKSAVDECC_AEM_COMMAND_ABORT_OPERATION (0x0035)
#define JDKSAVDECC_AEM_COMMAND_OPERATION_STATUS (0x0036)
#define JDKSAVDECC_AEM_COMMAND_AUTH_ADD_KEY (0x0037)
#define JDKSAVDECC_AEM_COMMAND_AUTH_DELETE_KEY (0x0038)
#define JDKSAVDECC_AEM_COMMAND_AUTH_GET_KEY_LIST (0x0039)
#define JDKSAVDECC_AEM_COMMAND_AUTH_GET_KEY (0x003a)
#define JDKSAVDECC_AEM_COMMAND_AUTH_ADD_KEY_TO_CHAIN (0x003b)
#define JDKSAVDECC_AEM_COMMAND_AUTH_DELETE_KEY_FROM_CHAIN (0x003c)
#define JDKSAVDECC_AEM_COMMAND_AUTH_GET_KEYCHAIN_LIST (0x003d)
#define JDKSAVDECC_AEM_COMMAND_AUTH_GET_IDENTITY (0x003e)
#define JDKSAVDECC_AEM_COMMAND_AUTH_ADD_TOKEN (0x003f)
#define JDKSAVDECC_AEM_COMMAND_AUTH_DELETE_TOKEN (0x0040)
#define JDKSAVDECC_AEM_COMMAND_AUTHENTICATE (0x0041)
#define JDKSAVDECC_AEM_COMMAND_DEAUTHENTICATE (0x0042)
#define JDKSAVDECC_AEM_COMMAND_ENABLE_TRANSPORT_SECURITY (0x0043)
#define JDKSAVDECC_AEM_COMMAND_DISABLE_TRANSPORT_SECURITY (0x0044)
#define JDKSAVDECC_AEM_COMMAND_ENABLE_STREAM_ENCRYPTION (0x0045)
#define JDKSAVDECC_AEM_COMMAND_DISABLE_STREAM_ENCRYPTION (0x0046)
#define JDKSAVDECC_AEM_COMMAND_SET_MEMORY_OBJECT_LENGTH (0x0047)
#define JDKSAVDECC_AEM_COMMAND_GET_MEMORY_OBJECT_LENGTH (0x0048)
#define JDKSAVDECC_AEM_COMMAND_SET_STREAM_BACKUP (0x0049)
#define JDKSAVDECC_AEM_COMMAND_GET_STREAM_BACKUP (0x004a)
#define JDKSAVDECC_AEM_COMMAND_EXPANSION (0x7fff)

/*@}*/

#endif

